# This file was generated by GoReleaser. DO NOT EDIT.
cask "gplay" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gplay"]
    end
  end

  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "296de05234f5aa3851c2b84178f0e45d34c59a6d02051c2588ed8d37e38b0805"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c21487daf2b0528544c9bc5c44fdb09fbded769b70887770885b25aa2db5d86e"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "10a77337bf6376b9badc597f5c82ead236ad3fc3dbf40a3ad1934aa3ae14fc1d"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ecdb2d7559470fcdbdbecb06832f341d270048eca304dee75d161943543adc0"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gplay"
  desc "Fast, lightweight CLI for the Google Play Developer API."
  homepage "https://gplay.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gplay"

  # No zap stanza required
end
