# This file was generated by GoReleaser. DO NOT EDIT.
cask "gplay" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gplay"]
    end
  end

  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "7c1fd24d5beba4ee88c7468d90551232a025df5b3a22340e9b2f233a859fb2cc"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5119cc6fdc64c3ab377a24442f818c905e6034e9f15bba7a508642b3cf4172fd"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbd4bd681b82b69bf64f8dd9efa1491f4885b525dc88373c22c2753e3e263f92"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "edf87c68d6b5ec8b57320834d9eda0a6972219f3684a983b6f7ad493e9439583"
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v#{version}/gplay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gplay"
  desc "Fast, lightweight CLI for the Google Play Developer API."
  homepage "https://gplay.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gplay"

  # No zap stanza required
end
