# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gplay < Formula
  desc "Fast, lightweight CLI for the Google Play Developer API."
  homepage "https://gplay.sh"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v1.4.1/gplay_1.4.1_darwin_amd64.tar.gz"
      sha256 "809752cb9bfd659c79a72ca4a42980cdfc0092fcd414eb73a2fce0fe0170db82"

      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v1.4.1/gplay_1.4.1_darwin_arm64.tar.gz"
      sha256 "940749391c63925ed5ee72da341e5b178d3ddf0538b506290c170ac45476614e"

      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v1.4.1/gplay_1.4.1_linux_amd64.tar.gz"
      sha256 "000d86c3c19148723b714c17b4ccaf4f011785b7bdf40ffa3ac9300825057d03"
      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v1.4.1/gplay_1.4.1_linux_arm64.tar.gz"
      sha256 "1a6c3827c4dc47ebb01b4dfba21bdeaebc42cc8c9384db68bca7ab7a58911b78"
      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  test do
    system "#{bin}/gplay", "version"
  end
end
