# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gplay < Formula
  desc "Fast, lightweight CLI for the Google Play Developer API."
  homepage "https://gplay.sh"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.7.0/gplay_0.7.0_darwin_amd64.tar.gz"
      sha256 "031533fabde1d652422d71ce28b258342bb6b18eb9a720a6d0db06dfc2041259"

      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.7.0/gplay_0.7.0_darwin_arm64.tar.gz"
      sha256 "59e3f606ea4198fb35ae4c02a24e009b6ab71a0b70d3ef2cbff68a790b2d2833"

      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.7.0/gplay_0.7.0_linux_amd64.tar.gz"
      sha256 "64e4597a6caf9578fae63dee2c8fff7d51bac334cf1634e21af1ef9ab0742193"
      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.7.0/gplay_0.7.0_linux_arm64.tar.gz"
      sha256 "52c44b655f5eea301b801ab8c635bd08b19a94594a711d4cea805f821c93b9f0"
      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  test do
    system "#{bin}/gplay", "version"
  end
end
