# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gplay < Formula
  desc "Fast, lightweight CLI for the Google Play Developer API."
  homepage "https://gplay.sh"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.14.0/gplay_0.14.0_darwin_amd64.tar.gz"
      sha256 "02d5a82d213115d6d7155ec7cd3246929c2828ec44787e88eda038b5a6ae5513"

      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.14.0/gplay_0.14.0_darwin_arm64.tar.gz"
      sha256 "6211f7a68adf768e08983f1a2c9162af96a8d9833126038a2612633379d51d02"

      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.14.0/gplay_0.14.0_linux_amd64.tar.gz"
      sha256 "7c8f34766f17e54cb8da4ce60212ea047492b3709fcab7c2fc535237fd1e1ef0"
      define_method(:install) do
        bin.install "gplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PollyGlot/google-play-cli/releases/download/v0.14.0/gplay_0.14.0_linux_arm64.tar.gz"
      sha256 "89bd798adc590887fe1529ee064be11510a4fa688b698dac9d0096cc9aae4ce8"
      define_method(:install) do
        bin.install "gplay"
      end
    end
  end

  test do
    system "#{bin}/gplay", "version"
  end
end
